kind: Service
apiVersion: v1beta3
metadata:
  name: app1-service
  labels:
    name: app1-service
    app: app1
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 80
      protocol: TCP
      nodePort: 32001
  sessionAffinity: ClientIP
  selector:
    app: app1
    version: v1


