kind: Service
apiVersion: v1beta3
metadata:
  name: wildfly-service
  labels:
    name: wildfly-service
    app: employees
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 32002
  sessionAffinity: ClientIP
  selector:
    app: employees


